# Site settings
# in the templates available like {{ site.myvariable }}.
title: Lily Paris
email: contato@lily.paris
brand: Lily Paris
headline: Design, elegância e exclusividade
description: > # this means to ignore newlines until "baseurl:"
  Lily Paris
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wogdalker.github.io" # the base hostname & protocol for your site
copyright: 2020 Lily Paris, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: contato@lily.paris
twitter: https://www.twitter.com/LilyParisDecor
#phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

